name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '35 23 * * 5'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/*'

permissions:
  contents: read

jobs:
  scorecard:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    uses: dafneb/.github/.github/workflows/scorecard.yml@2447bb5e1b5f31b2c534e3590cdc543a93576db2
    secrets: inherit
