name: Scorecard supply-chain security

on:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  # To guarantee Maintained check is occasionally updated. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    - cron: '35 23 * * 5'
  push:
    branches:
      - 'main'

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  scorecard:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    uses: dafneb/.github/.github/workflows/scorecard.yml@ad3e2b8ac3d3ea759a88bb8a0e507991f5c7ba9a
    secrets: inherit
