name: Code scan for Python using Snyk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - 'main'
      - 'development'
      - 'stable'
      - 'release/v*"'
      - 'feature/*'
      - 'issue/*'
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches:
      - 'main'
      - 'stable'
      - 'release/v*"'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  security:
    name: Snyk Code Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true # To make sure that SARIF upload gets called even if there are vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: snyk.sarif
