name: Snyk Container Scan

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'stable'
      - 'release/v*"'
      - 'feature/*'
      - 'issue/*'
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches:
      - 'main'
      - 'stable'
      - 'development'
      - 'release/v*"'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  azure:
    name: Snyk Container Scan (Azure)
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: dafneb/.github/.github/workflows/snyk-container-scan.yml@main
    with:
      working_directory: "./connectors/external-import/azure"
      image_name: "dafneb/connector-azure-inventory"
    secrets: inherit
