name: Snyk Container Scan

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'stable'
      - 'release/v*"'
      - 'feature/*'
      - 'issue/*'
    paths-ignore:
      - '.github/workflows/*'
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches:
      - 'main'
      - 'stable'
      - 'development'
      - 'release/v*"'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  azure:
    name: Snyk Container Scan (Azure)
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: dafneb/.github/.github/workflows/snyk-container-scan.yml@902a99fd805393744d6d7a8018045a108f3ce7a2
    with:
      working_directory: "./connectors/external-import/azure"
      image_name: "dafneb/connector-azure-inventory"
    secrets: inherit
